### ISSUE TITLE
USB phpvirtualbox

### ISSUE THREAD

**Issue by jefferson-94** [phpvirtualbox/phpvirtualbox#165]
When mark to release usb for a machine, the error vistualbox

![01](https://user-images.githubusercontent.com/38264031/56226814-70edf480-604a-11e9-8242-2de9e61a28b4.png)
![03](https://user-images.githubusercontent.com/38264031/56226815-70edf480-604a-11e9-8463-e154f78e9daf.png)

**Comment by VVD** [comment]
What version of VirtualBox and phpvirtualbox?

**Comment by grupojpr** [comment]
phpVirtualBox 5.2-0 -/- VirtualBox 5.2.x compatible

Virtual Box 5.2.26 (128414)

**Comment by chotaire** [comment]
Can "Details" be clicked to get more info? Also check your webserver error logs. In any case, we need more info.

**Comment by marius-wieschollek** [comment]
I think it might be the same as the error i'm getting when trying to attach an usb device:

```
docker-phpvirtualbox | 2022/07/18 15:48:40 [error] 15#15: *395740 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function IConsole::attachUSBDevice(), 1 passed in /var/www/endpoints/lib/vboxconnector.php on line 1214 and exactly 2 expected in /var/www/endpoints/lib/vboxServiceWrappers.php:6177
docker-phpvirtualbox | Stack trace:
docker-phpvirtualbox | #0 /var/www/endpoints/lib/vboxconnector.php(1214): IConsole->attachUSBDevice()
docker-phpvirtualbox | #1 /var/www/endpoints/lib/vboxconnector.php(951): vboxconnector->remote_consoleUSBDeviceAttach()
docker-phpvirtualbox | #2 /var/www/endpoints/api.php(316): vboxconnector->__call()
docker-phpvirtualbox | #3 {main}
docker-phpvirtualbox |   thrown in /var/www/endpoints/lib/vboxServiceWrappers.php on line 6177" while reading response header from upstream, client: 172.20.0.10, server: localhost, request: "POST /endpoints/api.php HTTP/1.0", upstream: "fastcgi://127.0.0.1:9000", host: "my-vbox-host", referrer: "https://my-vbox-host/"
```
(from the log of the docker container)

The function attachUSBDevice requires `$arg_captureFilename` as the second argument, but remote_consoleUSBDeviceAttach in the vboxconnector.php only passes an id as the first.
