### ISSUE TITLE
Ajax error: parsererror

### ISSUE THREAD

**Issue by PabloVSouza** [phpvirtualbox/phpvirtualbox#84]
I've just did a clean install of Ubuntu Server 17.10 with Virtualbox 5.2, and i'm getting the following error on PHPVirtualbox

```
Fatal error:  Uncaught ArgumentCountError: Too few arguments to function VBox_Enum::__construct(), 0 passed in /var/www/html/endpoints/lib/vboxconnector.php on line 2522 and exactly 2 expected in /var/www/html/endpoints/lib/vboxServiceWrappers.php:225
Stack trace:
#0 /var/www/html/endpoints/lib/vboxconnector.php(2522): VBox_Enum->__construct()
#1 /var/www/html/endpoints/lib/vboxconnector.php(951): vboxconnector->remote_vboxGetEnumerationMap(Array)
#2 /var/www/html/endpoints/api.php(316): vboxconnector->__call('vboxGetEnumerat...', Array)
#3 {main}
  thrown in /var/www/html/endpoints/lib/vboxServiceWrappers.php on line 225
```

**Comment by model-err** [comment]
The link can't be used…It seems the version 5.2 is disabled?
