### ISSUE TITLE
Cannot login to vboxwebsrv

### ISSUE THREAD

**Issue by 3PO** [phpvirtualbox/phpvirtualbox#89]
Hi,

I'm using VirtualBox 5.2.6 on Gentoo Linux and i installed phpvirtualbox for git, but i connot login.

This is the issue form the Browser:

    Exception Object
    (
        [message:protected] => Error logging in to vboxwebsrv.
        [string:Exception:private] => 
        [code:protected] => 64
        [file:protected] => /var/www/localhost/htdocs/phpvirtualbox/endpoints/api.php
        [line:protected] => 134
        [trace:Exception:private] => Array
            (
            )
    
        [previous:Exception:private] => 
    )

In the Logfile i only can see this issue:

`Jan 25 22:27:57 [vboxwebsrv] pam_securetty(login:auth): cannot determine user's tty`

Any suggestions where are my fault?

**Comment by tom077** [comment]
Hi,

First, check that you followed all the instructions from the [Wiki](https://github.com/phpvirtualbox/phpvirtualbox/wiki).

Then, the most probable reason is that you have provided a wrong username/password in you config.php :
`var $username = 'the name of the user running vboxwebsrv;
var $password = 'its password';`

**Comment by 3PO** [comment]
vboxwebsrv is running as root:

    server01 ~ # ps aux |grep vboxwebsrv
    root      4985  0.0  0.0  13144   916 pts/0    S+   23:05   0:00 grep --colour=auto vboxwebsrv
    root     17778  0.0  0.1 572620 19464 ?        Ssl  20:54   0:00 /usr/lib64/virtualbox/vboxwebsrv -H localhost -p 18083 -t 20 -i 5
    server01 ~ #

And the config.php is correct:

    /* Username / Password for system user that runs VirtualBox */
    var $username = 'root';
    var $password = 'MYROOTPASSWORD';

**Comment by tom077** [comment]
OK thanks.

Just to be sure that your problem is not related to the way Virtuabox is build with Gentoo (or to the dependencies used to build it), you can try to download [`the Virtualbox SDK`](https://download.virtualbox.org/virtualbox/5.2.6/VirtualBoxSDK-5.2.6-120293.zip).

Unzip the VirtualBoxSDK-5.2.6-120293.zip file.
Copy these file to the same folder :
sdk/bindings/webservice/vboxweb.wsdl
sdk/bindings/webservice/vboxwebService.wsdl
sdk/bindings/webservice/php/lib/vboxServiceWrappers.php
sdk/bindings/webservice/php/samples/clienttest.php

edit the file "clienttest.php"

`$virtualbox = $websessionManager->logon("root","YOUR ROOT PASSWORD");`

run `php -f clienttest.php`

If you get a "Uncaught SoapFault exception" or any other error, your problem is not related to phpvirtualbox.

**Comment by 3PO** [comment]
I get this issue: 

    server01 ~ # php -f /usr/lib64/virtualbox/sdk/bindings/webservice/php/samples/clienttest.php
    PHP Warning:  require_once(./vboxServiceWrappers.php): failed to open stream: No such file or directory in /usr/lib64/virtualbox/sdk/bindings/webservice/php/samples/clienttest.php on line 39
    PHP Fatal error:  require_once(): Failed opening required './vboxServiceWrappers.php' (include_path='.:/usr/share/php7:/usr/share/php') in /usr/lib64/virtualbox/sdk/bindings/webservice/php/samples/clienttest.php on line 39
    server01 ~ #

**Comment by tom077** [comment]
I would recommend you to submit your clienttest.php issue to the [Virtualbox bug tracker](https://www.virtualbox.org/wiki/Bugtracker).

But the strange thing is that I can reproduce the same clienttest.php stack trace if I deliberately use a wrong password in `$virtualbox = $websessionManager->logon("","");`

```
PHP Fatal error:  Uncaught SoapFault exception: [SOAP-ENV:Client]  in /srv/http-ssl/vboxServiceWrappers.php:12469
Stack trace:
#0 /srv/http-ssl/vboxServiceWrappers.php(12469): SoapClient->__soapCall('IWebsessionMana...', Array)
#1 /srv/http-ssl/clienttest.php(47): IWebsessionManager->logon('vbox', '#########')
#2 {main}
  thrown in /srv/http-ssl/vboxServiceWrappers.php on line 12469
```


Maybe you could try another Linux account (not root) to run vboxwebsrv and log in.
I use a dedicated user "vbox".

**Comment by tom077** [comment]
I just tried to run vboxwebsrv as root instead of my dedicated user "vbox".

I get the same stack trace :

```
PHP Fatal error:  Uncaught SoapFault exception: [SOAP-ENV:Client]  in /srv/http-ssl/vboxServiceWrappers.php:12469
Stack trace:
#0 /srv/http-ssl/vboxServiceWrappers.php(12469): SoapClient->__soapCall('IWebsessionMana...', Array)
#1 /srv/http-ssl/clienttest.php(47): IWebsessionManager->logon('root', 'good password')
#2 {main}
  thrown in /srv/http-ssl/vboxServiceWrappers.php on line 12469
```

It seems that vboxwebsrv doesn't accept connection if run as root.

**Comment by tom077** [comment]
It is even more obvious if you look at you vboxwebsrv log file :

```
00:05:39.159198 SQW05    Processing connection from IP=127.0.0.1 socket=13 (1 out of 5 threads idle)
00:05:39.159305 SQW05    -- entering __vbox__IWebsessionManager_USCORElogon
00:05:40.068779 SQW03    authenticate(): result of AuthEntry('root', [9]): 0 (access DENIED)
00:05:40.068836 SQW03    Access for user 'root' denied
```

**Comment by 3PO** [comment]
>It seems that vboxwebsrv doesn't accept connection if run as root.

Yes, that's the trick! :)

I added a user "vbox" and added this user to group "vboxusers".

    useradd vbox
    passwd vbox
    gpasswd -a vbox vboxusers

I've edited the config file: 

    # User under which vboxwebsrv is running
    VBOXWEBSRV_USER="vbox"
 
Then i restarted the service "vboxwebsrv".

Now the vboxwebsrv service is running as user vbox:

    server01 ~ # ps aux |grep vbox
    vbox     26415  0.2  0.1 895512 23288 ?        Ssl  20:14   0:00 /usr/lib64/virtualbox/vboxwebsrv -H localhost -p 18083 -t 20 -i 5
    vbox     26435  0.0  0.0 121412 11008 ?        S    20:14   0:00 /usr/lib64/virtualbox/VBoxXPCOMIPCD
    vbox     26440  0.1  0.1 544028 19172 ?        Sl   20:14   0:00 /usr/lib64/virtualbox/VBoxSVC --auto-shutdown
    root     30394  0.0  0.0  13144   884 pts/5    S+   20:16   0:00 grep --colour=auto vbox
    server01 ~ #

i changed the config.php to:

    /* Username / Password for system user that runs VirtualBox */
    var $username = 'vbox';
    var $password = 'vbox';

And now it works fine! 👍 

![2018-01-26_202907](https://user-images.githubusercontent.com/945108/35457277-9e8a6db8-02d8-11e8-8e12-540e23e9789b.png)

BTW:
For using https, i followed this [Wiki](https://wiki.gentoo.org/wiki/PhpVirtualBox), and login via https works as well. 👍

Maybe you can implant some code, that checks, if "vboxwebsrv" is running as root?
Additional this should added to the README and Wiki. ;)

PS:
clienttest.php gives a issue anyway:

    server01 tmp # php -f clienttest.php
    PHP Notice:  Undefined property: stdClass::$returnval in /tmp/vboxServiceWrappers.php on line 1147
    
    server01 tmp # 

But it works, so who cares.  :)

**Comment by tom077** [comment]
Glad to read that.

Thank you for having highlighted that new issue. Really helpful.

**Comment by afkpaul** [comment]
You can always disable the vboxwebsrv authentication. 

# change External authentication library from 'VBoxAuth' to 'null'
su - vbox -c "VBoxManage setproperty websrvauthlibrary null"

**Comment by CpServiceSpb** [comment]
I have Ubuntu 18.04 x64 LTS with Apache2 and Virtualbox 6.1.18r142142 installed.
I added vboxuser user with /home/vboxuser folder and appropriate password.
Also I made /etc/vbox folder as well as /etc/vbox/vbox.conf file with the following content:
```
default_policy = deny

vboxuser = {
    allow = true
}
```
And I inserted to /etc/default/virtualbox the following:
```
LOAD_VBOXDRV_MODULE=1
SHUTDOWN_USERS=""
SHUTDOWN=poweroff

# For autostart
VBOXAUTOSTART_DB=/etc/vbox
VBOXAUTOSTART_CONFIG=/etc/vbox/vbox.conf

## For Web UI
VBOXWEB_USER=vboxuser
VBOXWEB_HOST=127.0.0.1
VBOXWEB_PORT=18083
VBOX_HOME=/home/vbox
VBOXWEB_LOGFILE=/var/log/vboxweb/vboxweb.log
VBOXWEB_PIDFILE=/var/run/vboxweb/vboxweb.pid
```

Then I downloaded phpvirtualbox as the latest git version due to 6.1 version and put vboxuser as user and respective password of vboxuser as a password and set www-data:www-data permissions for the phpvirtualbox folder and its files.
For folders and its content:
/etc/vbox
/home/vbox
/var/log/vboxweb
/var/run/vboxweb
/hdd/mount/vmachines (where VMs are placed) 
I set vboxuserLvboxusers permissions as well as to /etc/default/virtualbox

All were started fine, that is:
```
vboxuser /usr/lib/virtualbox/vboxwebsrv --background -H 127.0.0.1 -p 18083 -F /var/log/vboxweb/vboxweb.log
vboxuser /usr/lib/virtualbox/VBoxXPCOMIPCD
vboxuser /usr/lib/virtualbox/VBoxSVC --auto-shutdown
```

phpvirtualbox login page is opened fine.
I put admin/admin and get the old error:
```
Exception Object
(
    [message:protected] => Error logging in to vboxwebsrv.
    [string:Exception:private] => 
    [code:protected] => 64
    [file:protected] => /var/www/html/vms/endpoints/api.php
    [line:protected] => 134
    [trace:Exception:private] => Array
        (
        )

    [previous:Exception:private] => 
)
```
and in log error: **Access for the 'vboxuser' is denied.**

Where and what is wrong ?

**Comment by h6w** [comment]
@CpServiceSpb It looks like you created a user "vboxuser" but then you asked phpvirtualbox to look in "/home/vbox" which is not vboxuser's home but vbox's home.  vboxuser's home is "/etc/vboxuser"

**Comment by CpServiceSpb** [comment]
I don' t "vbox" user at all, I have "vboxuser" user.
And vboxuser:x:aaa:bbb:Virtualbox user:/home/vbox:/bin/bash, that is
"/home/vbox" home folder for "vboxuser" user.
Then there is
VBOXAUTOSTART_DB=/etc/vbox
VBOXAUTOSTART_CONFIG=/etc/vbox/vbox.conf

and at the same time
VBOX_HOME=/home/vbox
in /etc/default/virtualbox

File "VirtualBox.xml" with the VMs list is in the
"/home/vbox/.config/VirtualBox" folder.

I really don' t understand where do I have to specify /home/vbox or what
folders/files do I have to move and where to ?

пн, 5 апр. 2021 г. в 03:23, h6w ***@***.***>:

**Comment by CpServiceSpb** [comment]
I made test - changed
VBOXAUTOSTART_DB=/home/vbox
VBOXAUTOSTART_CONFIG=/home/vbox/vbox.conf
in /etc/default/virtualbox
and move /etc/vbox with its content respectively.
And all worked.
Anyway, thanks.

But there is one more point of thinking - I cannot access under
vboxuser:vboxusers to physical partition connected to the VM by vmdk file,
generated by VBoxManage internalcommands createrawvmdk -filename
$VMDKPATH/$VMDKNAME -rawdisk $DISK.
What minimum necessary rights have to be set for the /dev/sdaX partition ?

пн, 5 апр. 2021 г. в 12:12, CpServiceSPb ***@***.***>:

**Comment by h6w** [comment]
@CpServiceSpb Accessing raw partitions is a Virtualbox issue and outside the scope of PHPVirtualBox.  You may have some luck googling "virtualbox accessing raw disks permissions".
